version: '3.8'
services:
  streamlit_app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
    volumes:
      - .:/app/files/markethub
      - data_volume:/root/IA/markethub
volumes:
  data_volume: